(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const PHONES = 'IY IH EH AE AA AO AH UH UW ER AY AW EY OW OY W Y R L M N NG F TH S SH V DH Z ZH HH P B T D K G CH JH'.split(' ');
  const SHAPES=['smooth','siney','buzz','hollow','square','reed','pulse','metallic'];
  const PRESETS = {
    balanced:{basePitchHz:185,brightness:1,breath:.035,warmth:1,roughness:.015,sourceShape:'smooth',tractScale:1,vowelSpace:1,f1Scale:1,f2Scale:1,f3Scale:1,harmonicTilt:1.15,oddEvenBias:0,pitchDriftCents:4,vibratoDepthCents:0,consonantEdge:1,fricativeSharpness:1,stopPunch:1,stopVoice:1,nasalDarkness:1,liquidDarkness:1,diphthongGlideStart:.52,diphthongCurve:1,durationScale:1,identityVariation:.16},
    bright:{basePitchHz:210,brightness:1.3,breath:.022,warmth:.82,roughness:.008,sourceShape:'pulse',tractScale:1.07,vowelSpace:1.08,f1Scale:1,f2Scale:1.06,f3Scale:1.08,harmonicTilt:.96,oddEvenBias:.08,pitchDriftCents:3,vibratoDepthCents:1,consonantEdge:1.28,fricativeSharpness:1.24,stopPunch:1.12,stopVoice:.92,nasalDarkness:.88,liquidDarkness:.9,diphthongGlideStart:.56,diphthongCurve:1.18,durationScale:.94,identityVariation:.2},
    warm:{basePitchHz:160,brightness:.78,breath:.025,warmth:1.3,roughness:.02,sourceShape:'hollow',tractScale:.95,vowelSpace:.94,f1Scale:.98,f2Scale:.94,f3Scale:.91,harmonicTilt:1.34,oddEvenBias:.24,pitchDriftCents:7,vibratoDepthCents:2,consonantEdge:.82,fricativeSharpness:.78,stopPunch:.9,stopVoice:1.12,nasalDarkness:1.18,liquidDarkness:1.18,diphthongGlideStart:.49,diphthongCurve:.86,durationScale:1.06,identityVariation:.2},
    soft:{basePitchHz:192,brightness:.86,breath:.145,warmth:1.08,roughness:.004,sourceShape:'siney',tractScale:1,vowelSpace:.9,f1Scale:1,f2Scale:.98,f3Scale:.96,harmonicTilt:1.48,oddEvenBias:-.05,pitchDriftCents:9,vibratoDepthCents:2.5,consonantEdge:.67,fricativeSharpness:.68,stopPunch:.74,stopVoice:.82,nasalDarkness:1.04,liquidDarkness:1.08,diphthongGlideStart:.58,diphthongCurve:1.1,durationScale:1.12,identityVariation:.22},
    tiny:{basePitchHz:260,brightness:1.45,breath:.032,warmth:.72,roughness:.008,sourceShape:'square',tractScale:1.15,vowelSpace:1.16,f1Scale:1.04,f2Scale:1.12,f3Scale:1.13,harmonicTilt:.92,oddEvenBias:.42,pitchDriftCents:6,vibratoDepthCents:3,consonantEdge:1.34,fricativeSharpness:1.38,stopPunch:1.18,stopVoice:.78,nasalDarkness:.76,liquidDarkness:.82,diphthongGlideStart:.6,diphthongCurve:1.35,durationScale:.88,identityVariation:.24},
    deep:{basePitchHz:122,brightness:.66,breath:.035,warmth:1.42,roughness:.03,sourceShape:'buzz',tractScale:.83,vowelSpace:.9,f1Scale:.94,f2Scale:.84,f3Scale:.82,harmonicTilt:1.28,oddEvenBias:-.12,pitchDriftCents:8,vibratoDepthCents:1.5,consonantEdge:.8,fricativeSharpness:.74,stopPunch:1.18,stopVoice:1.28,nasalDarkness:1.32,liquidDarkness:1.34,diphthongGlideStart:.46,diphthongCurve:.78,durationScale:1.1,identityVariation:.22},
    robot:{basePitchHz:180,brightness:1.1,breath:.002,warmth:.9,roughness:0,sourceShape:'metallic',tractScale:1.02,vowelSpace:.78,f1Scale:1.02,f2Scale:1,f3Scale:1.04,harmonicTilt:.86,oddEvenBias:-.34,pitchDriftCents:0,vibratoDepthCents:0,consonantEdge:1.15,fricativeSharpness:1.08,stopPunch:1.34,stopVoice:.72,nasalDarkness:.9,liquidDarkness:.92,diphthongGlideStart:.64,diphthongCurve:1.55,durationScale:.92,identityVariation:.04},
    glass:{basePitchHz:220,brightness:1.58,breath:.012,warmth:.62,roughness:.002,sourceShape:'siney',tractScale:1.12,vowelSpace:1.24,f1Scale:.94,f2Scale:1.14,f3Scale:1.2,harmonicTilt:1.62,oddEvenBias:-.18,pitchDriftCents:2,vibratoDepthCents:4,consonantEdge:1.45,fricativeSharpness:1.48,stopPunch:.92,stopVoice:.68,nasalDarkness:.68,liquidDarkness:.72,diphthongGlideStart:.66,diphthongCurve:1.45,durationScale:1.02,identityVariation:.18},
    velvet:{basePitchHz:150,brightness:.68,breath:.07,warmth:1.48,roughness:.012,sourceShape:'smooth',tractScale:.91,vowelSpace:.84,f1Scale:.96,f2Scale:.89,f3Scale:.86,harmonicTilt:1.55,oddEvenBias:.1,pitchDriftCents:10,vibratoDepthCents:3,consonantEdge:.62,fricativeSharpness:.58,stopPunch:.8,stopVoice:1.18,nasalDarkness:1.3,liquidDarkness:1.38,diphthongGlideStart:.44,diphthongCurve:.72,durationScale:1.16,identityVariation:.22},
    buzzy:{basePitchHz:175,brightness:1.16,breath:.01,warmth:.92,roughness:.05,sourceShape:'buzz',tractScale:.99,vowelSpace:1.04,f1Scale:1.03,f2Scale:1,f3Scale:1.02,harmonicTilt:.78,oddEvenBias:.32,pitchDriftCents:16,vibratoDepthCents:1,consonantEdge:1.12,fricativeSharpness:1.1,stopPunch:1.22,stopVoice:1.12,nasalDarkness:1,liquidDarkness:1,diphthongGlideStart:.5,diphthongCurve:.92,durationScale:.98,identityVariation:.26},
    nasal:{basePitchHz:188,brightness:.92,breath:.02,warmth:1.05,roughness:.014,sourceShape:'reed',tractScale:1,vowelSpace:.92,f1Scale:.93,f2Scale:1.06,f3Scale:.92,harmonicTilt:1.08,oddEvenBias:.18,pitchDriftCents:8,vibratoDepthCents:2,consonantEdge:.92,fricativeSharpness:.88,stopPunch:.96,stopVoice:1.02,nasalDarkness:1.55,liquidDarkness:1.12,diphthongGlideStart:.54,diphthongCurve:1,durationScale:1.04,identityVariation:.24},
    alien:{basePitchHz:205,brightness:1.18,breath:.045,warmth:.78,roughness:.035,sourceShape:'reed',tractScale:1.18,vowelSpace:1.36,f1Scale:.86,f2Scale:1.18,f3Scale:.88,harmonicTilt:.98,oddEvenBias:-.42,pitchDriftCents:30,vibratoDepthCents:10,consonantEdge:1.2,fricativeSharpness:1.26,stopPunch:1.16,stopVoice:.78,nasalDarkness:.82,liquidDarkness:.74,diphthongGlideStart:.34,diphthongCurve:1.8,durationScale:1.08,identityVariation:.3},
    chip:{basePitchHz:305,brightness:1.62,breath:0,warmth:.58,roughness:0,sourceShape:'square',tractScale:1.22,vowelSpace:1.08,f1Scale:1.05,f2Scale:1.17,f3Scale:1.2,harmonicTilt:.72,oddEvenBias:.78,pitchDriftCents:0,vibratoDepthCents:0,consonantEdge:1.55,fricativeSharpness:1.52,stopPunch:1.4,stopVoice:.58,nasalDarkness:.58,liquidDarkness:.64,diphthongGlideStart:.72,diphthongCurve:1.7,durationScale:.76,identityVariation:.1},
    cavern:{basePitchHz:105,brightness:.56,breath:.055,warmth:1.62,roughness:.045,sourceShape:'hollow',tractScale:.74,vowelSpace:.78,f1Scale:.9,f2Scale:.78,f3Scale:.72,harmonicTilt:1.42,oddEvenBias:.5,pitchDriftCents:14,vibratoDepthCents:3,consonantEdge:.68,fricativeSharpness:.62,stopPunch:1.3,stopVoice:1.42,nasalDarkness:1.55,liquidDarkness:1.58,diphthongGlideStart:.38,diphthongCurve:.64,durationScale:1.2,identityVariation:.24}
  };
  const FIELD={basePitchHz:'apPitch',brightness:'apBrightness',warmth:'apWarmth',breath:'apBreath',roughness:'apRough',sourceShape:'apSourceShape',tractScale:'apTract',vowelSpace:'apVowelSpace',f1Scale:'apF1',f2Scale:'apF2',f3Scale:'apF3',harmonicTilt:'apTilt',oddEvenBias:'apOddEven',pitchDriftCents:'apDrift',vibratoDepthCents:'apVibrato',consonantEdge:'apConsonant',fricativeSharpness:'apFricative',stopPunch:'apStopPunch',stopVoice:'apStopVoice',nasalDarkness:'apNasal',liquidDarkness:'apLiquid',diphthongGlideStart:'apGlideStart',diphthongCurve:'apGlideCurve',durationScale:'apDuration',identityVariation:'apIdentityVar'};
  const slug=s=>String(s||'agent-voice').toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'')||'agent-voice';
  const num=id=>Number($(id).value)||0;
  function parseJson(id,label,fallback){const t=$(id)?.value.trim();if(!t)return fallback;try{return JSON.parse(t)}catch(e){throw new Error(label+': '+e.message)}}
  function overrides(){return parseJson('apOverrides','Phoneme override JSON',{})}
  function recipe(){
    const engineType=$('apEngineType').value,engineConfig=parseJson('apEngineConfig','Engine config JSON',{}),engine={type:engineType,id:engineType==='command'?slug($('apEngineCustomId').value||'custom-engine'):$('apEngineId').value,config:engineConfig};
    if(engineType==='command')engine.command=parseJson('apEngineCommand','External command JSON',[]);
    if(engineType==='command'&&(!Array.isArray(engine.command)||!engine.command.length))throw new Error('External command engine needs a JSON command array.');
    const profile={theme:$('apProfileTheme').value,accent:$('apProfileAccent').value.trim(),accent2:$('apProfileAccent2').value.trim(),status:$('apProfileStatus').value.trim(),bio:$('apProfileBio').value.trim(),badges:$('apProfileBadges').value.split(',').map(x=>x.trim()).filter(Boolean),links:parseJson('apProfileLinks','Profile links JSON',[]),banner:$('apProfileBanner').value.trim()?{source:$('apProfileBanner').value.trim()}:null,background:$('apProfileBackground').value.trim()?{source:$('apProfileBackground').value.trim()}:null,stickers:parseJson('apProfileStickers','Profile stickers JSON',[]),extraAssets:parseJson('apProfileExtras','Extra profile assets JSON',[])};
    return {format:'agentpatch-recipe-3',id:slug($('apId').value||$('apName').value),name:$('apName').value.trim()||'Agent Voice',author:$('apAuthor').value.trim(),description:$('apDescription').value.trim(),introSentence:$('apIntro').value.trim(),icon:$('apIcon').value.trim(),tags:$('apTags').value.split(',').map(x=>x.trim()).filter(Boolean),engine,preset:$('apPreset').value,style:{basePitchHz:num('apPitch')||185,brightness:num('apBrightness')||1,warmth:num('apWarmth')||1,breath:num('apBreath'),roughness:num('apRough'),sourceShape:$('apSourceShape').value,tractScale:num('apTract')||1,vowelSpace:num('apVowelSpace')||1,f1Scale:num('apF1')||1,f2Scale:num('apF2')||1,f3Scale:num('apF3')||1,harmonicTilt:num('apTilt')||1.15,oddEvenBias:num('apOddEven'),pitchDriftCents:num('apDrift'),vibratoDepthCents:num('apVibrato'),vibratoRateHz:5.3,consonantEdge:num('apConsonant')||1,fricativeSharpness:num('apFricative')||1,stopPunch:num('apStopPunch')||1,stopVoice:num('apStopVoice')||1,nasalDarkness:num('apNasal')||1,liquidDarkness:num('apLiquid')||1,diphthongGlideStart:num('apGlideStart')||.52,diphthongCurve:num('apGlideCurve')||1,durationScale:num('apDuration')||1,identityVariation:num('apIdentityVar')},variation:{phonePitchCents:num('apPhonePitch'),phoneFormantPct:num('apPhoneFormant'),phoneDurationPct:num('apPhoneDuration'),phoneGainDb:.35},timing:{vowels:num('apTimeVowels')||1,diphthongs:num('apTimeDiph')||1,nasals:num('apTimeNasals')||1,fricatives:num('apTimeFric')||1,stops:num('apTimeStops')||1,affricates:num('apTimeAff')||1,glides:num('apTimeGlides')||1},phonemeOverrides:overrides(),characterArt:$('apArt').value.trim()?{source:$('apArt').value.trim()}:null,profile,seed:Math.round(num('apSeed')||5606),sampleRate:32000,defaults:{speed:1,pitchSemitones:0,overlapMs:24,wordGapMs:45,punctuationGapMs:260}};
  }
  function applyStyle(p){for(const[k,id] of Object.entries(FIELD))if(p[k]!==undefined&&$(id))$(id).value=p[k];update()}
  function update(){
    let r;try{r=recipe();$('apStatus').className='small'}catch(e){$('apStatus').textContent=e.message;$('apStatus').className='small browser-pack-bad';return}
    $('apId').value=r.id;const ext=r.engine.type==='command'?' --allow-external-engine':'';
    $('apCommands').textContent=`python agentpatch.py build ${r.id}.agentpatch.json --output mainvoices/${r.id} --zip ${r.id}-mainvoice.zip${ext}\n\n# inspect the resolved identity + selected engine\npython agentpatch.py identity ${r.id}.agentpatch.json --json\n\n# branch the identity while keeping the selected engine\npython agentpatch.py variant ${r.id}.agentpatch.json --strength 0.75 --out ${r.id}-variant.agentpatch.json\n\n# validate before publishing\npython agentpatch.py validate mainvoices/${r.id} --json`;
    $('apIdentitySummary').textContent=`engine ${r.engine.type}:${r.engine.id}\n${r.style.sourceShape} source · ${Math.round(r.style.basePitchHz)} Hz\ntract ${r.style.tractScale.toFixed(2)} · vowel space ${r.style.vowelSpace.toFixed(2)}\nF1/F2/F3 ${r.style.f1Scale.toFixed(2)} / ${r.style.f2Scale.toFixed(2)} / ${r.style.f3Scale.toFixed(2)}\nedge ${r.style.consonantEdge.toFixed(2)} · fricative ${r.style.fricativeSharpness.toFixed(2)} · stop ${r.style.stopPunch.toFixed(2)}\nseed ${r.seed} · identity variation ${r.style.identityVariation.toFixed(2)}${r.characterArt?`\nart ${r.characterArt.source}`:''}`;
    $('apEngineCommandWrap').hidden=r.engine.type!=='command';$('apCustomEngineIdWrap').hidden=r.engine.type!=='command';$('apBuiltinEngineWrap').hidden=r.engine.type==='command';
    const accent=/^#[0-9a-f]{3,8}$/i.test(r.profile.accent)?r.profile.accent:'#ff7a18',accent2=/^#[0-9a-f]{3,8}$/i.test(r.profile.accent2)?r.profile.accent2:accent;
    const badges=(r.profile.badges||[]).slice(0,8);$('apProfilePreview').style.setProperty('--ap-accent',accent);$('apProfilePreview').style.setProperty('--ap-accent2',accent2);$('apProfilePreview').innerHTML=`<div class="profile-preview-name">${r.icon||'✦'} ${r.name}</div>${r.profile.status?`<div class="profile-preview-status">● ${r.profile.status.replace(/[<>]/g,'')}</div>`:''}${r.profile.bio?`<div class="small" style="margin-top:8px">${r.profile.bio.replace(/[<>]/g,'')}</div>`:''}${badges.length?`<div class="profile-preview-badges">${badges.map(x=>`<span>${String(x).replace(/[<>]/g,'')}</span>`).join('')}</div>`:''}<div class="small" style="margin-top:10px">${r.profile.theme} · ${r.engine.type}:${r.engine.id}${r.profile.banner?.source?' · banner':''}${r.profile.background?.source?' · background':''}</div>`;
  }
  function download(){let r;try{r=recipe()}catch(e){$('apStatus').textContent=e.message;return}const blob=new Blob([JSON.stringify(r,null,2)+'\n'],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${r.id}.agentpatch.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);$('apStatus').textContent=`Downloaded ${a.download}.`}
  async function copy(text,msg){try{await navigator.clipboard.writeText(text);$('apStatus').textContent=msg}catch{$('apStatus').textContent='Clipboard access was blocked; select the text manually instead.'}}
  function task(){const r=recipe();const ext=r.engine.type==='command'?` This recipe uses an external command engine; review its command before running AgentPatch with --allow-external-engine.`:'';return `Create a distinct MainVoice voice named "${r.name}" with ID "${r.id}" using AgentPatch 3. Read AGENTPATCH.md first. Respect the selected engine instead of forcing every voice through AgentPatch's formant engine.${ext} The engine may be built-in, an external command/plugin, or you may replace all generated WAVs with output from another audio system and use AgentPatch only for metadata/validation/packaging. Preserve SVG/PNG/WebP profile assets, decorations, badges, links, and colors from the recipe. Run \`python agentpatch.py identity <recipe> --json\`, build/provide all 39 WAVs, run \`python agentpatch.py validate <voice-folder> --json\`, fix errors, then pack it. Do not modify other MainVoice source or voicebanks.\n\nRecipe:\n${JSON.stringify(r,null,2)}`}
  function randomize(){const rnd=(a,b)=>a+Math.random()*(b-a),pick=a=>a[Math.floor(Math.random()*a.length)];$('apSeed').value=Math.floor(rnd(1000,2147480000));$('apSourceShape').value=pick(SHAPES);$('apPitch').value=Math.round(rnd(105,285));$('apBrightness').value=rnd(.58,1.58).toFixed(2);$('apWarmth').value=rnd(.58,1.55).toFixed(2);$('apBreath').value=rnd(0,.16).toFixed(3);$('apRough').value=rnd(0,.07).toFixed(3);$('apTract').value=rnd(.76,1.24).toFixed(2);$('apVowelSpace').value=rnd(.72,1.35).toFixed(2);$('apF1').value=rnd(.86,1.14).toFixed(2);$('apF2').value=rnd(.82,1.18).toFixed(2);$('apF3').value=rnd(.84,1.16).toFixed(2);$('apTilt').value=rnd(.72,1.58).toFixed(2);$('apOddEven').value=rnd(-.65,.65).toFixed(2);$('apDrift').value=Math.round(rnd(0,28));$('apConsonant').value=rnd(.65,1.45).toFixed(2);$('apFricative').value=rnd(.62,1.5).toFixed(2);$('apStopPunch').value=rnd(.7,1.5).toFixed(2);$('apNasal').value=rnd(.7,1.5).toFixed(2);$('apLiquid').value=rnd(.72,1.45).toFixed(2);$('apGlideStart').value=rnd(.3,.72).toFixed(2);$('apDuration').value=rnd(.82,1.2).toFixed(2);$('apIdentityVar').value=rnd(.12,.38).toFixed(2);update();$('apStatus').textContent='Randomized the actual timbre/articulation identity — not only the seed.'}
  $('apPreset').innerHTML=Object.keys(PRESETS).map(x=>`<option>${x}</option>`).join('');$('apPhones').innerHTML=PHONES.map(p=>`<span>${p}</span>`).join('');$('apEngineConfig').value='{}';$('apProfileLinks').value='[]';$('apProfileStickers').value='[]';$('apProfileExtras').value='[]';
  $('apPreset').onchange=e=>applyStyle(PRESETS[e.target.value]||PRESETS.balanced);
  document.querySelectorAll('input,select,textarea').forEach(el=>el.addEventListener('input',update));
  $('apDownload').onclick=download;$('apCopyJson').onclick=()=>{try{copy(JSON.stringify(recipe(),null,2),'Recipe JSON copied.')}catch(e){$('apStatus').textContent=e.message}};$('apCopyTask').onclick=()=>{try{copy(task(),'Agent task copied.')}catch(e){$('apStatus').textContent=e.message}};$('apRandomize').onclick=randomize;
  applyStyle(PRESETS.balanced);update();
})();
