window.PHONEMES = [
  {c:'IY',w:'see',type:'vowel',sound:'the long “ee” sound',say:'Smile slightly and hold a clean “eeee.”',tip:'Keep it steady, like the vowel in “see,” not “sit.”'},
  {c:'IH',w:'sit',type:'vowel',sound:'the short “ih” sound',say:'Relax your mouth and say the vowel from “sit.”',tip:'It should be looser and shorter than IY.'},
  {c:'EH',w:'set',type:'vowel',sound:'the “eh” sound',say:'Say a relaxed “ehhh,” like the vowel in “set.”',tip:'Do not let it turn into “ay.”'},
  {c:'AE',w:'cat',type:'vowel',sound:'the “a” sound in cat',say:'Open your mouth and hold the vowel from “cat.”',tip:'Use your natural accent. The app is learning your voice, not forcing an accent.'},
  {c:'AA',w:'spa',type:'vowel',sound:'the open “ah” sound',say:'Open your jaw and hold “ahhh,” like “spa.”',tip:'If AA and AO are close in your accent, that is completely fine.'},
  {c:'AO',w:'law',type:'vowel',sound:'the “aw” sound',say:'Say the rounded vowel from “law.”',tip:'Usually a bit more rounded than AA.'},
  {c:'AH',w:'but',type:'vowel',sound:'the “uh” sound',say:'Say the central “uh” vowel in “but.”',tip:'Keep it natural and not too long.'},
  {c:'UH',w:'book',type:'vowel',sound:'the vowel in book',say:'Say the short rounded vowel in “book.”',tip:'Shorter and looser than UW in “boot.”'},
  {c:'UW',w:'boot',type:'vowel',sound:'the long “oo” sound',say:'Round your lips and hold “oooo,” like “boot.”',tip:'Keep the vowel clean and steady.'},
  {c:'ER',w:'bird',type:'vowel',sound:'the “er” sound',say:'Hold the r-colored vowel in “bird.”',tip:'For most American speakers this is basically a held “errr.”'},
  {c:'AY',w:'bite',type:'vowel',sound:'the “eye” glide',say:'Say the whole vowel glide from “bite.”',tip:'Start open and glide upward. Record the full glide as one unit.'},
  {c:'AW',w:'now',type:'vowel',sound:'the “ow” glide',say:'Say “ow!” like the vowel in “now.”',tip:'Let it move naturally from open to rounded.'},
  {c:'EY',w:'say',type:'vowel',sound:'the “ay” glide',say:'Say the vowel in “say.”',tip:'Let it glide naturally rather than freezing it.'},
  {c:'OW',w:'go',type:'vowel',sound:'the “oh” glide',say:'Say the vowel in “go.”',tip:'End a little more rounded than you started.'},
  {c:'OY',w:'boy',type:'vowel',sound:'the “oy” glide',say:'Say the vowel glide in “boy.”',tip:'Record the whole glide as one sound.'},
  {c:'W',w:'way',type:'consonant',sound:'the W at the start of way',say:'Round your lips like a tiny “oo” and make the W onset from “way.”',tip:'Keep this very short. Avoid adding a full vowel after it.'},
  {c:'Y',w:'yes',type:'consonant',sound:'the Y at the start of yes',say:'Make the consonant Y onset from “yes.”',tip:'Think “yyy” rather than saying the letter name “why.”'},
  {c:'R',w:'red',type:'consonant',sound:'the R at the start of red',say:'Make your normal English R and hold it briefly.',tip:'Do not add a big “uh” afterward.'},
  {c:'L',w:'let',type:'consonant',sound:'the L at the start of let',say:'Put your tongue near the ridge behind your upper teeth and hold a short “llll.”',tip:'A tiny bit of vowel is okay, but try to keep the L obvious.'},
  {c:'M',w:'me',type:'consonant',sound:'the M at the start of me',say:'Close your lips and hum “mmmm” briefly.',tip:'Keep it voiced and steady.'},
  {c:'N',w:'no',type:'consonant',sound:'the N at the start of no',say:'Hold a short “nnnn” with your tongue near the ridge behind your teeth.',tip:'Do not turn it into “en.”'},
  {c:'NG',w:'sing',type:'consonant',sound:'the NG at the end of sing',say:'Hold the ending sound from “sing.”',tip:'This is one sound, not N plus a hard G.'},
  {c:'F',w:'fee',type:'consonant',sound:'the F at the start of fee',say:'Touch your top teeth lightly to your lower lip and blow “ffff.”',tip:'No vocal-cord buzz.'},
  {c:'TH',w:'thin',type:'consonant',sound:'the unvoiced TH in thin',say:'Put your tongue lightly between/against your teeth and blow air.',tip:'No buzz. Think “thin,” not “this.”'},
  {c:'S',w:'see',type:'consonant',sound:'the S at the start of see',say:'Make a clean short “ssss.”',tip:'Keep your voice off.'},
  {c:'SH',w:'she',type:'consonant',sound:'the SH at the start of she',say:'Make a short “shhhh.”',tip:'Lips slightly rounded usually helps.'},
  {c:'V',w:'vee',type:'consonant',sound:'the V at the start of vee',say:'Use the F mouth position, but turn your voice on: “vvvv.”',tip:'You should feel a buzz.'},
  {c:'DH',w:'this',type:'consonant',sound:'the voiced TH in this',say:'Use the TH tongue position and add voice.',tip:'Think “this,” not “thin.”'},
  {c:'Z',w:'zoo',type:'consonant',sound:'the Z at the start of zoo',say:'Make a short buzzing “zzzz.”',tip:'Like S, but voiced.'},
  {c:'ZH',w:'vision',type:'consonant',sound:'the middle sound in vision',say:'Make the voiced partner of SH: “zhhhh.”',tip:'You can also find it in “measure.”'},
  {c:'HH',w:'he',type:'consonant',sound:'the H at the start of he',say:'Make a soft breathy “hhh.”',tip:'Do not force the air; a normal gentle H is enough.'},
  {c:'P',w:'pea',type:'consonant',sound:'the P at the start of pea',say:'Make one tiny P release, like the beginning of “pea.”',tip:'P cannot be held. A tiny bit of the following vowel is okay.'},
  {c:'B',w:'bee',type:'consonant',sound:'the B at the start of bee',say:'Make one short B release.',tip:'Like P but voiced. A tiny bit of following vowel is fine.'},
  {c:'T',w:'tea',type:'consonant',sound:'the T at the start of tea',say:'Make one quick T release with your tongue.',tip:'Do not try to hold T.'},
  {c:'D',w:'dee',type:'consonant',sound:'the D at the start of dee',say:'Make one quick voiced D release.',tip:'A tiny bit of following vowel is okay.'},
  {c:'K',w:'key',type:'consonant',sound:'the K at the start of key',say:'Make one quick K release at the back of your mouth.',tip:'Do not try to hold K.'},
  {c:'G',w:'go',type:'consonant',sound:'the hard G at the start of go',say:'Make one quick hard-G release.',tip:'Use the G in “go,” not the J-like G in “giant.”'},
  {c:'CH',w:'cheese',type:'consonant',sound:'the CH at the start of cheese',say:'Make one short “ch” burst.',tip:'It naturally contains a stop followed by an SH-like release.'},
  {c:'JH',w:'judge',type:'consonant',sound:'the J at the start of judge',say:'Make one short English J sound.',tip:'This is the voiced partner of CH.'}
];
window.PHONEME_MAP = Object.fromEntries(window.PHONEMES.map(p => [p.c, p]));
